// Initial tracker data - will be stored in Supabase
export const INITIAL_DATA = {
  lastUpdated: new Date().toISOString(),
  
  debt: {
    atInauguration: 36.18,
    baseline: 38.43,
    baselineDate: '2026-01-07T00:00:00Z',
    perSecond: 92912.33,
    perHousehold: 285127,
    source: 'Joint Economic Committee / Treasury Dept',
  },
  
  wealth: {
    current: 6.6,
    previous: 2.3,
    rank: 581,
    source: 'Forbes',
    breakdown: [
      { category: 'Cryptocurrencies', value: 7.1, note: 'Up to (NYT July 2025)' },
      { category: 'Stocks, Bonds & Cash', value: 2.2 },
      { category: 'Real Estate & Business', value: 1.3 },
      { category: 'Debts', value: -0.64 },
    ],
  },
  
  golf: {
    golfClubVisits2025: 88,
    totalPropertyVisits: 99,
    estimatedCost2025: 110600000,
    costPerMarALagoTrip: 3400000,
    costPerBedminsterTrip: 1100000,
    scotlandTripCost: 10000000,
    firstTermTotal: 151500000,
    firstTermVisits: 261,
    secretServiceToTrump: 2000000,
    secretServiceToTrump2ndTerm: 100000,
    source: 'GAO 2019 Report • CREW • HuffPost • Trump Golf Tracker',
    sourceUrl: 'https://www.citizensforethics.org/reports-investigations/crew-investigations/secret-service-has-spent-nearly-100k-at-trump-properties/',
  },
  
  selfDealing: {
    secretServiceAtProperties2ndTerm: 100000,
    secretServiceFirstTerm: 2000000,
    foreignGovFirstTerm: 7800000,
    foreignCountries: 20,
    overchargeRate: '300%',
    cryptoFees: 427000000,
    source: 'CREW • House Oversight • GAO • American Oversight',
    sourceUrl: 'https://www.citizensforethics.org/reports-investigations/crew-reports/trumps-term-2-corruption-by-the-numbers-more-golf-trips-more-foreign-visitors-and-more-profits/',
  },
  
  iceVictims: [
    { 
      id: 'renee-good',
      name: 'Renée Good', 
      age: 37, 
      citizenship: 'US Citizen',
      date: 'January 7, 2026',
      location: 'Minneapolis, MN',
      agency: 'ICE',
      details: 'Shot by ICE agent Jonathan Ross while in her vehicle during "Operation Metro Surge." Mother of a 6-year-old. Video shows agent filming with phone before shooting.',
      officialResponse: 'DHS claims self-defense',
      witnessAccount: 'Mayor Frey: "narrative that this was done in self-defense is garbage"',
      sources: ['Wikipedia', 'NPR', 'CNN', 'Al Jazeera'],
    },
    { 
      id: 'alex-pretti',
      name: 'Alex Pretti', 
      age: 37, 
      citizenship: 'US Citizen',
      date: 'January 24, 2026',
      location: 'Minneapolis, MN',
      agency: 'Border Patrol',
      details: 'ICU nurse at VA hospital. Shot while observing immigration enforcement. Bystander video shows him helping a woman who was pushed down, then being tackled and shot 4 times in the back.',
      officialResponse: 'DHS claims he "tried to assassinate federal law enforcement"',
      witnessAccount: 'Sworn statements say he did not brandish gun, was helping woman get up',
      sources: ['Wikipedia', 'NPR', 'CBS News', 'Al Jazeera'],
    },
  ],
  
  iceStats: {
    totalShootings: 30,
    shootingDeaths: 8,
    usCitizensKilled: 2,
    usCitizensShot: 5,
    detentionDeaths2025: 32,
    detentionDeaths2026: 6,
    note: 'December 2025 was deadliest month on record. 2025 had highest ICE detention deaths since 2004.',
    source: 'Wikipedia / ACLU / Vera Institute / NBC News / PBS',
    sourceUrl: 'https://en.wikipedia.org/wiki/List_of_shootings_by_U.S._immigration_agents_in_the_second_Trump_administration',
  },
  
  brokenPromises: [
    {
      id: 'groceries-down',
      category: 'Economy',
      promise: 'Bring grocery prices "way down"',
      quote: '"I won on groceries. I won an election based on that."',
      datePromised: 'December 2024',
      location: 'Meet the Press',
      deadline: 'Ongoing',
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'Grocery prices UP 2.4% year-over-year (Dec 2025)',
        'December 2025: largest monthly grocery spike since Aug 2022',
        'Coffee up 20%, ground beef up 15.5%, eggs spiked 15.2%',
        'Trump still claims prices are "way down" despite BLS data',
      ],
      sources: ['CNN Fact Check', 'BLS', 'ABC News', 'Axios'],
    },
    {
      id: 'manufacturing-jobs',
      category: 'Economy',
      promise: 'Manufacturing jobs "roaring back"',
      quote: '"Jobs and factories will come roaring back into our country."',
      datePromised: 'April 2, 2025',
      location: 'Liberation Day tariff announcement',
      deadline: null,
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'Lost 72,000+ manufacturing jobs since Liberation Day',
        'Manufacturing declined 7 straight months',
        '73% of manufacturers cite tariffs as top business challenge',
        'Clean energy manufacturing: $18B+ in projects cancelled',
      ],
      sources: ['Washington Post', 'CBC', 'Center for American Progress', 'NAM'],
    },
    {
      id: 'energy-50',
      category: 'Economy',
      promise: 'Cut energy bills in HALF within 12 months',
      quote: '"I will cut your energy and electricity prices in half, 50% — 5-0 — within 12 months of taking the oath"',
      datePromised: 'August 14, 2024',
      location: 'Asheville, NC rally',
      deadline: 'January 20, 2026',
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 20,
      reality: [
        'Gasoline: Down ~20% (not 50%) - global oil prices, not policy',
        'Electricity: UP 9% from January to August 2025',
        'Average family paid $124 MORE for utilities since inauguration',
        'Household energy costs 6.2% higher year-over-year',
      ],
      sources: ['NPR', 'CNN Fact Check', 'BLS', 'EIA'],
    },
    {
      id: 'ukraine-24h',
      category: 'Foreign Policy',
      promise: 'End Ukraine war within 24 HOURS',
      quote: '"I\'ll get that done within 24 hours. Everyone says, \'Oh, no, you can\'t.\' Absolutely I can."',
      datePromised: 'July 2023 - November 2024',
      location: '53+ times at rallies',
      deadline: 'January 21, 2025',
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'War continues after 370+ days in office',
        'Trump now says it was "in jest" and "an exaggeration"',
        'Extended deadline to 100 days, then 6 months, now indefinite',
        'Secretary Rubio suggested US may "back away" from negotiations',
      ],
      sources: ['CNN (53 instances documented)', 'Time Magazine', 'PolitiFact'],
    },
    {
      id: 'day-one-inflation',
      category: 'Economy',
      promise: 'End inflation on DAY ONE',
      quote: '"Starting on day one, we will end inflation and make America affordable again"',
      datePromised: 'August 9, 2024',
      location: 'Bozeman, MT rally',
      deadline: 'January 20, 2025',
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'CPI accelerated to 3.0% after taking office (up from 2.9%)',
        'Eggs spiked 15.2% in one month (Jan 2025)',
        'Groceries: 2.7% increase - largest non-pandemic gain since 2015',
        'Goldman Sachs: Consumers bearing 50%+ of tariff costs',
      ],
      sources: ['BLS', 'Newsweek', 'CNN', 'Goldman Sachs'],
    },
    {
      id: 'epstein-files',
      category: 'Transparency',
      promise: 'Release the Epstein files',
      quote: '"I guess I would [release the Epstein files]"',
      datePromised: 'June 2024',
      location: 'Fox & Friends, Lex Fridman Podcast',
      deadline: 'No specific date given',
      status: 'MOSTLY BROKEN',
      statusColor: '#ff6600',
      progress: 30,
      reality: [
        'Administration resisted release for months',
        'Congress forced his hand with 427-1 vote (Epstein Files Transparency Act)',
        'DOJ MISSED legal deadline (December 19, 2025)',
        '5.2 million pages still unreviewed as of late December',
        'Released files show Trump flew on Epstein plane 8 times (more than known)',
      ],
      sources: ['NPR', 'Axios', 'CNBC', 'Wikipedia'],
    },
    {
      id: 'drill-baby-drill',
      category: 'Energy',
      promise: '"Drill, baby, drill" - Unleash energy production',
      quote: '"We\'re going to drill, baby, drill"',
      datePromised: 'Throughout 2024 campaign',
      location: 'Multiple rallies',
      deadline: null,
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'Active drilling rigs DOWN 6%+ year-over-year',
        'Oil prices too low (~$50s) to justify new drilling',
        'His own pressure for low prices is PREVENTING drilling',
        'Oil industry got all 12 lobbying priorities except this',
      ],
      sources: ['NPR', 'American Petroleum Institute'],
    },
    {
      id: 'medicare-medicaid',
      category: 'Healthcare',
      promise: 'Protect Medicare and Medicaid - NO CUTS',
      quote: '"I will never do anything that will jeopardize or hurt Social Security or Medicare"',
      datePromised: 'Multiple interviews 2024',
      location: 'Various',
      deadline: null,
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'Signed largest healthcare cut in history',
        '17 million Americans projected to lose healthcare',
        'Let ACA tax credits expire - premiums spiked 50%+',
        'Treasury Secretary Bessent admitted bill is "backdoor for privatizing Social Security"',
      ],
      sources: ['CBS News', 'Reuters', 'Democrats.org'],
    },
    {
      id: 'tariffs-pay-everything',
      category: 'Economy',
      promise: 'Tariff revenue to replace income tax / fund everything',
      quote: '"I believe at some point in the not too distant future, you won\'t even have income tax to pay because the money we\'re taking in is so great"',
      datePromised: 'December 2025',
      location: 'Various interviews',
      deadline: null,
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 5,
      reality: [
        'Promised ~$6T in tariff-funded programs; 2025 revenue: $264B',
        'Income tax raised $2.7T in 2025 vs $264B tariffs',
        'Tariffs cover <5% of promised expenditures',
        'Washington Post: promises exceed 22x actual tariff revenue',
      ],
      sources: ['Washington Post', 'Treasury', 'Cato Institute'],
    },
    {
      id: 'lower-costs-day-one',
      category: 'Economy',
      promise: 'Make America affordable again on Day One',
      quote: '"Starting on day one, we will end inflation and make America affordable again, to bring down the prices of all goods"',
      datePromised: 'August 9, 2024',
      location: 'Bozeman, MT rally',
      deadline: 'January 20, 2025',
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'Households paid $2,120 MORE in 2025 due to inflation (Warren Report)',
        'Bottom 20% of households hit hardest (5%+ of income)',
        'Electricity bills: +$123 | Groceries: +$150 per household',
        'Fed: Tariffs responsible for inflation rising above 2% target',
      ],
      sources: ['Senate Banking Committee', 'Fortune', 'Federal Reserve', 'Goldman Sachs'],
    },
    {
      id: 'jobs-coming-back',
      category: 'Economy',
      promise: 'Jobs coming back / best economy ever',
      quote: '"We\'re going to have the greatest economy in the history of the world"',
      datePromised: '2024 campaign',
      location: 'Multiple rallies',
      deadline: null,
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        '2025 saw lowest average monthly job growth since 2003 (excluding recessions)',
        'December 2025: Job gains cooled significantly',
        '57% of consumers expect economy to weaken in 2026 (Deloitte)',
        'Only 44% of Republicans rate economy as excellent/good (Bloomberg)',
      ],
      sources: ['WSJ', 'Bloomberg', 'MarketWatch', 'Deloitte'],
    },
    {
      id: 'no-deportation-errors',
      category: 'Immigration',
      promise: 'Only deport criminals, protect legal residents',
      quote: '"We\'re not looking to deport legal residents... we\'re looking for the bad ones, the criminals"',
      datePromised: '2024 campaign',
      location: 'Various',
      deadline: null,
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'Kilmar Abrego Garcia: Legal resident wrongfully deported to El Salvador prison',
        'Administration admitted "administrative error" but refused to return him',
        'Defied Supreme Court order to "facilitate" his return',
        'Now prosecuting him after failed challenge—court called it "vindictive"',
      ],
      sources: ['Supreme Court', 'PBS', 'CBS News', 'NPR'],
    },
  ],
  
  // Constitutional concerns - robust baseline
  constitutionalConcerns: [
    {
      id: 'defying-courts',
      amendment: 'ARTICLE III / SEPARATION OF POWERS',
      title: 'Defying 1 in 3 Court Orders',
      description: 'Washington Post analysis found the administration defied, delayed, or manipulated rulings in 57 of 165 lawsuits (roughly 1/3) where courts ruled against it—unprecedented for any presidential administration.',
      examples: [
        'Kilmar Abrego Garcia: Refused return despite Supreme Court order',
        'Continued deportation flights after temporary restraining orders',
        'Chief Judge Boasberg: "willful disregard" of court orders',
        'Judge Xinis: administration showed "no tolerance for compliance"',
      ],
      quote: 'The Constitution does not tolerate willful disobedience of judicial orders—especially by officials of a coordinate branch who have sworn an oath to uphold it.',
      quoteSource: 'Chief U.S. District Judge James E. Boasberg',
      status: 'ONGOING',
      statusColor: '#ef4444',
      sources: ['Washington Post', 'AP News', 'Just Security', 'Federal Court Records'],
    },
    {
      id: 'due-process',
      amendment: '5TH & 14TH AMENDMENTS',
      title: 'Deportations Without Due Process',
      description: '225+ judges have ruled in 700+ cases that mandatory immigration detention policy likely violates law and the right to due process. Legal residents deported without hearings.',
      examples: [
        'Abrego Garcia: Deported to foreign prison without hearing despite legal status',
        'F-1 visa students: 100+ lawsuits over revocations without process',
        'New detention policy deprives opportunity for immigration court hearings',
        'Citizens detained by federal agents without identification procedures',
      ],
      quote: 'No person shall be... deprived of life, liberty, or property, without due process of law.',
      quoteSource: 'Fifth Amendment',
      status: 'ONGOING - 700+ RULINGS',
      statusColor: '#f59e0b',
      sources: ['Politico', 'ACLU', 'Just Security', 'Federal Courts'],
    },
    {
      id: 'birthright-citizenship',
      amendment: '14TH AMENDMENT',
      title: 'Birthright Citizenship Executive Order',
      description: 'EO 14160 attempts to deny citizenship to U.S.-born children—contradicting 14th Amendment text and 127 years of Supreme Court precedent (U.S. v. Wong Kim Ark, 1898).',
      examples: [
        'Blocked by multiple federal courts',
        'Supreme Court hearing expected Feb-Apr 2026',
        'ACLU, LULAC, and states filed immediate lawsuits',
        '6-3 Supreme Court limited injunctions to named plaintiffs only',
      ],
      quote: 'All persons born or naturalized in the United States, and subject to the jurisdiction thereof, are citizens of the United States.',
      quoteSource: 'Fourteenth Amendment, Section 1',
      status: 'IN COURTS - SCOTUS 2026',
      statusColor: '#3b82f6',
      sources: ['Ballotpedia', 'SCOTUSblog', 'Rutgers Law School', 'ACLU'],
    },
    {
      id: 'emoluments',
      amendment: 'ARTICLE I, SECTION 9',
      title: 'Foreign Emoluments Without Congressional Consent',
      description: 'Trump Organization revised ethics policy in 2025 to explicitly allow foreign transactions. Qatar plane deal ($7M+), foreign government hotel stays, and business deals continue without congressional consent.',
      examples: [
        '$7.8M from 20+ foreign governments documented during first term',
        'Qatar plane deal: Senate resolution calls it "illegal emolument"',
        'Vietnam: $1.5B golf complex fast-tracked during tariff negotiations',
        'Serbia: Half-billion-dollar Trump Hotel cleared after election',
      ],
      quote: 'No Person holding any Office of Profit or Trust under them, shall, without the Consent of the Congress, accept of any present, Emolument, Office, or Title, of any kind whatever, from any King, Prince, or foreign State.',
      quoteSource: 'Foreign Emoluments Clause',
      status: 'NO CONGRESSIONAL CONSENT',
      statusColor: '#22c55e',
      sources: ['House Oversight Committee', 'CREW', 'AEI', 'Brennan Center'],
    },
    {
      id: 'first-amendment',
      amendment: '1ST AMENDMENT',
      title: 'Attacks on Press and Protesters',
      description: 'Two U.S. citizens shot by federal agents at immigration protests. Multiple lawsuits from AP, NPR, PBS over press access bans. Calls to revoke broadcast licenses of critical networks.',
      examples: [
        'AP sued over Oval Office/Air Force One bans for using "Gulf of Mexico"',
        'NPR, PBS sued over funding threats',
        'Two citizens killed by federal agents at Minneapolis protests',
        'Journalists face access revocation for critical coverage',
      ],
      quote: 'Congress shall make no law... abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble.',
      quoteSource: 'First Amendment',
      status: 'MULTIPLE LAWSUITS',
      statusColor: '#8b5cf6',
      sources: ['Committee to Protect Journalists', 'PEN America', 'AP News', 'NPR'],
    },
    {
      id: 'doge-unconstitutional',
      amendment: 'ARTICLE I / SEPARATION OF POWERS',
      title: 'DOGE Mass Firings Without Congressional Authorization',
      description: 'Federal judge ruled OPM illegally directed mass firings of 25,000+ probationary employees. Congress established agencies; administration closing them without authorization.',
      examples: [
        '317,000 federal workforce reduction in 2025 (Bloomberg)',
        'Judge Alsup: OPM firings were unlawful',
        'USAID, Education Dept, HHS gutted without congressional approval',
        'Supreme Court stayed reinstatement orders, allowing cuts to continue',
      ],
      quote: 'OPM does not have any authority whatsoever under any statute in the history of the universe to hire and fire employees within another agency.',
      quoteSource: 'Federal Judge William Alsup',
      status: 'RULED ILLEGAL - SCOTUS ALLOWED',
      statusColor: '#ef4444',
      sources: ['NPR', 'Government Executive', 'Bloomberg', 'Protect Democracy'],
    },
    {
      id: 'equal-protection',
      amendment: '14TH AMENDMENT - EQUAL PROTECTION',
      title: 'Political Discrimination in Federal Grants',
      description: 'Court ruled DOE cancelled clean energy grants based on whether recipients lived in states that voted for Trump—"purposeful segregation based on electoral support."',
      examples: [
        'Jan 12, 2026: DC District Court rules unconstitutional',
        '"No explanation for how segregation advances government interest"',
        'Grants cancelled in non-Trump states; approved in Trump states',
        'Environmental Defense Fund lawsuit successful',
      ],
      quote: 'Defendants freely admit that they made grant-termination decisions primarily — if not exclusively — based on whether the awardee resided in a state whose citizens voted for President Trump in 2024.',
      quoteSource: 'U.S. District Court, D.C. (Jan 12, 2026)',
      status: 'RULED UNCONSTITUTIONAL',
      statusColor: '#ef4444',
      sources: ['EDF', 'Federal Court Decision', 'D.C. District Court'],
    },
    {
      id: 'j6-pardons',
      amendment: 'RULE OF LAW',
      title: 'Mass Pardons for Capitol Attack',
      description: 'Pardoned 1,500+ individuals convicted of January 6th crimes on first day in office, including seditious conspiracy convicts and those who assaulted 140+ police officers.',
      examples: [
        'Oath Keepers & Proud Boys leaders: seditious conspiracy sentences commuted',
        'Pardons for assault on police officers',
        'Judge Lamberth: "unconscionable" and "preposterous"',
        'DC Police Union condemned pardons',
      ],
      status: 'COMPLETED - DAY ONE',
      statusColor: '#ef4444',
      sources: ['DOJ Records', 'NPR', 'AP News', 'Federal Court Records'],
    },
    {
      id: 'inspector-general',
      amendment: 'CONGRESSIONAL OVERSIGHT',
      title: 'Illegal Firing of Inspectors General',
      description: 'Fired 17 Inspectors General without required 30-day congressional notice. Judge ruled firings unlawful but refused reinstatement.',
      examples: [
        'Sept 24, 2025: Judge Reyes ruled firings unlawful',
        'Required 30-day notice to Congress was not provided',
        'IGs provide independent oversight of executive agencies',
        'Court noted Trump would "simply re-fire them" after notice',
      ],
      status: 'RULED UNLAWFUL',
      statusColor: '#f59e0b',
      sources: ['Federal Court Records', 'Government Executive', 'NPR'],
    },
  ],
};
