// Initial tracker data - will be stored in Supabase
export const INITIAL_DATA = {
  lastUpdated: new Date().toISOString(),
  
  debt: {
    atInauguration: 36.18,
    baseline: 38.43,
    baselineDate: '2026-01-07T00:00:00Z',
    perSecond: 92912.33,
    perHousehold: 285127,
    source: 'Joint Economic Committee / Treasury Dept',
  },
  
  wealth: {
    current: 6.6,
    previous: 2.3,
    rank: 581,
    source: 'Forbes',
    breakdown: [
      { category: 'Cryptocurrencies', value: 7.1, note: 'Up to (NYT July 2025)' },
      { category: 'Stocks, Bonds & Cash', value: 2.2 },
      { category: 'Real Estate & Business', value: 1.3 },
      { category: 'Debts', value: -0.64 },
    ],
  },
  
  golf: {
    golfClubVisits2025: 88,
    totalPropertyVisits: 99,
    estimatedCost2025: 110600000,
    costPerMarALagoTrip: 3400000,
    costPerBedminsterTrip: 1100000,
    scotlandTripCost: 10000000,
    firstTermTotal: 151500000,
    firstTermVisits: 261,
    secretServiceToTrump: 2000000,
    secretServiceToTrump2ndTerm: 100000,
    source: 'GAO 2019 Report • CREW • HuffPost • Trump Golf Tracker',
    sourceUrl: 'https://www.citizensforethics.org/reports-investigations/crew-investigations/secret-service-has-spent-nearly-100k-at-trump-properties/',
  },
  
  selfDealing: {
    secretServiceAtProperties2ndTerm: 100000,
    secretServiceFirstTerm: 2000000,
    foreignGovFirstTerm: 7800000,
    foreignCountries: 20,
    overchargeRate: '300%',
    cryptoFees: 427000000,
    source: 'CREW • House Oversight • GAO • American Oversight',
    sourceUrl: 'https://www.citizensforethics.org/reports-investigations/crew-reports/trumps-term-2-corruption-by-the-numbers-more-golf-trips-more-foreign-visitors-and-more-profits/',
  },
  
  iceVictims: [
    { 
      id: 'renee-good',
      name: 'Renée Good', 
      age: 37, 
      citizenship: 'US Citizen',
      date: 'January 7, 2026',
      location: 'Minneapolis, MN',
      agency: 'ICE',
      details: 'Shot by ICE agent Jonathan Ross while in her vehicle during "Operation Metro Surge." Mother of a 6-year-old. Video shows agent filming with phone before shooting.',
      officialResponse: 'DHS claims self-defense',
      witnessAccount: 'Mayor Frey: "narrative that this was done in self-defense is garbage"',
      sources: ['Wikipedia', 'NPR', 'CNN', 'Al Jazeera'],
    },
    { 
      id: 'alex-pretti',
      name: 'Alex Pretti', 
      age: 37, 
      citizenship: 'US Citizen',
      date: 'January 24, 2026',
      location: 'Minneapolis, MN',
      agency: 'Border Patrol',
      details: 'ICU nurse at VA hospital. Shot while observing immigration enforcement. Bystander video shows him helping a woman who was pushed down, then being tackled and shot 4 times in the back.',
      officialResponse: 'DHS claims he "tried to assassinate federal law enforcement"',
      witnessAccount: 'Sworn statements say he did not brandish gun, was helping woman get up',
      sources: ['Wikipedia', 'NPR', 'CBS News', 'Al Jazeera'],
    },
  ],
  
  iceStats: {
    totalShootings: 27,
    shootingDeaths: 8,
    detentionDeaths2025: 32,
    detentionDeaths2026: 6,
    note: 'December 2025 was deadliest month on record',
    source: 'Wikipedia / ACLU / Vera Institute / AILA',
  },
  
  brokenPromises: [
    {
      id: 'groceries-down',
      category: 'Economy',
      promise: 'Bring grocery prices "way down"',
      quote: '"I won on groceries. I won an election based on that."',
      datePromised: 'December 2024',
      location: 'Meet the Press',
      deadline: 'Ongoing',
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'Grocery prices UP 2.4% year-over-year (Dec 2025)',
        'December 2025: largest monthly grocery spike since Aug 2022',
        'Coffee up 20%, ground beef up 15.5%, eggs spiked 15.2%',
        'Trump still claims prices are "way down" despite BLS data',
      ],
      sources: ['CNN Fact Check', 'BLS', 'ABC News', 'Axios'],
    },
    {
      id: 'manufacturing-jobs',
      category: 'Economy',
      promise: 'Manufacturing jobs "roaring back"',
      quote: '"Jobs and factories will come roaring back into our country."',
      datePromised: 'April 2, 2025',
      location: 'Liberation Day tariff announcement',
      deadline: null,
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'Lost 72,000+ manufacturing jobs since Liberation Day',
        'Manufacturing declined 7 straight months',
        '73% of manufacturers cite tariffs as top business challenge',
        'Clean energy manufacturing: $18B+ in projects cancelled',
      ],
      sources: ['Washington Post', 'CBC', 'Center for American Progress', 'NAM'],
    },
    {
      id: 'energy-50',
      category: 'Economy',
      promise: 'Cut energy bills in HALF within 12 months',
      quote: '"I will cut your energy and electricity prices in half, 50% — 5-0 — within 12 months of taking the oath"',
      datePromised: 'August 14, 2024',
      location: 'Asheville, NC rally',
      deadline: 'January 20, 2026',
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 20,
      reality: [
        'Gasoline: Down ~20% (not 50%) - global oil prices, not policy',
        'Electricity: UP 9% from January to August 2025',
        'Average family paid $124 MORE for utilities since inauguration',
        'Household energy costs 6.2% higher year-over-year',
      ],
      sources: ['NPR', 'CNN Fact Check', 'BLS', 'EIA'],
    },
    {
      id: 'ukraine-24h',
      category: 'Foreign Policy',
      promise: 'End Ukraine war within 24 HOURS',
      quote: '"I\'ll get that done within 24 hours. Everyone says, \'Oh, no, you can\'t.\' Absolutely I can."',
      datePromised: 'July 2023 - November 2024',
      location: '53+ times at rallies',
      deadline: 'January 21, 2025',
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'War continues after 370+ days in office',
        'Trump now says it was "in jest" and "an exaggeration"',
        'Extended deadline to 100 days, then 6 months, now indefinite',
        'Secretary Rubio suggested US may "back away" from negotiations',
      ],
      sources: ['CNN (53 instances documented)', 'Time Magazine', 'PolitiFact'],
    },
    {
      id: 'day-one-inflation',
      category: 'Economy',
      promise: 'End inflation on DAY ONE',
      quote: '"Starting on day one, we will end inflation and make America affordable again"',
      datePromised: 'August 9, 2024',
      location: 'Bozeman, MT rally',
      deadline: 'January 20, 2025',
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'CPI accelerated to 3.0% after taking office (up from 2.9%)',
        'Eggs spiked 15.2% in one month (Jan 2025)',
        'Groceries: 2.7% increase - largest non-pandemic gain since 2015',
        'Goldman Sachs: Consumers bearing 50%+ of tariff costs',
      ],
      sources: ['BLS', 'Newsweek', 'CNN', 'Goldman Sachs'],
    },
    {
      id: 'epstein-files',
      category: 'Transparency',
      promise: 'Release the Epstein files',
      quote: '"I guess I would [release the Epstein files]"',
      datePromised: 'June 2024',
      location: 'Fox & Friends, Lex Fridman Podcast',
      deadline: 'No specific date given',
      status: 'MOSTLY BROKEN',
      statusColor: '#ff6600',
      progress: 30,
      reality: [
        'Administration resisted release for months',
        'Congress forced his hand with 427-1 vote (Epstein Files Transparency Act)',
        'DOJ MISSED legal deadline (December 19, 2025)',
        '5.2 million pages still unreviewed as of late December',
        'Released files show Trump flew on Epstein plane 8 times (more than known)',
      ],
      sources: ['NPR', 'Axios', 'CNBC', 'Wikipedia'],
    },
    {
      id: 'drill-baby-drill',
      category: 'Energy',
      promise: '"Drill, baby, drill" - Unleash energy production',
      quote: '"We\'re going to drill, baby, drill"',
      datePromised: 'Throughout 2024 campaign',
      location: 'Multiple rallies',
      deadline: null,
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'Active drilling rigs DOWN 6%+ year-over-year',
        'Oil prices too low (~$50s) to justify new drilling',
        'His own pressure for low prices is PREVENTING drilling',
        'Oil industry got all 12 lobbying priorities except this',
      ],
      sources: ['NPR', 'American Petroleum Institute'],
    },
    {
      id: 'medicare-medicaid',
      category: 'Healthcare',
      promise: 'Protect Medicare and Medicaid - NO CUTS',
      quote: '"I will never do anything that will jeopardize or hurt Social Security or Medicare"',
      datePromised: 'Multiple interviews 2024',
      location: 'Various',
      deadline: null,
      status: 'BROKEN',
      statusColor: '#ff3333',
      progress: 0,
      reality: [
        'Signed largest healthcare cut in history',
        '17 million Americans projected to lose healthcare',
        'Let ACA tax credits expire - premiums spiked 50%+',
        'Treasury Secretary Bessent admitted bill is "backdoor for privatizing Social Security"',
      ],
      sources: ['CBS News', 'Reuters', 'Democrats.org'],
    },
  ],
};
